name: dpo_qwen_experiment
project: DPO
workspace: Bijan

environment:
    image: determinedai/environments:cuda-11.8-pytorch-2.0-gpu-0.27.1

hyperparameters:
  model_name: Qwen/Qwen2-0.5B
  dataset_name: tiny_shakespeare
  batch_size: 8
  num_epochs: 3
  learning_rate: 2e-5
  beta: 0.1
  max_length: 128
  num_workers: 2

resources:
  resource_pool: A100
  slots_per_trial: 1  # Adjust this based on your available GPUs

entrypoint: model_def:DPOTrial

searcher:
  name: single
  metric: validation_loss
  smaller_is_better: true
  max_length:
    batches: 1000

max_restarts: 0